apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f6434e92c30f4a44
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: efs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:containerpath
    - name: efs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-static
    persistentVolumeClaim:
      claimName: efs-static  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30007         